// Generated by CoffeeScript 1.5.0

$(document).ready(function() {
  var food, start, user;
  user = void 0;
  food = void 0;
  $(".radio_on_map").change(function() {
    if (user === void 0) {
      user = $(this).val();
      $('#' + user.replace(':', '_')).append('<div id="agent" />');
      return $(this).hide();
    } else {
      food = $(this).val();
      $(".radio_on_map").hide();
      $('#' + food.replace(':', '_')).append('<div id="food" />');
      return start(user, food);
    }
  });
  return start = function(user, food) {
    return $.ajax({
      type: "POST",
      url: "?request=astar/calculateSteps",
      data: {
        'map': jsonMap,
        'user': user,
        'food': food
      },
      success: function(data) {
        var i, map, walkRoute, walker,
          _this = this;
        walkRoute = JSON.parse(data);
        map = JSON.parse(jsonMap);
        i = 0;
        walker = function() {
          $('#agent').remove();
          $('#' + walkRoute[i].replace(':', '_')).append('<div id="agent" />');
          if (food === walkRoute[i]) {
            $('#food').remove();
          }
          if (map[walkRoute[i]] === "1") {
            alert("AAAAA LAVA");
          }
          i++;
          if (i < walkRoute.length) {
            return setTimeout(walker, 500);
          }
        };
        return setTimeout(walker, 500);
      }
    });
  };
});
