// Generated by CoffeeScript 1.5.0

$(document).ready(function() {
  var food, user;
  user = void 0;
  food = void 0;
  return $("input[type=radio]").change(function() {
    var cssClass, name, val;
    val = $(this).val();
    name = $(this).attr('name');
    cssClass = (function() {
      switch (val) {
        case "0":
          return "grass";
        case "1":
          return "lava";
        case "2":
          return "water";
        case "3":
          return "mountain";
        case "4":
          return "sand";
      }
    })();
    return $('#' + name.replace(':', '_')).removeClass('lava sand water grass mountain').addClass(cssClass);
  });
});
